server:
  port: 9999

spring:
  application:
    name: product-catalog

  datasource:
    platform: postgresql
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:compasso}
    username: ${DATABASE_USERNAME:usuario}
    password: ${DATABASE_PASSWORD:senhaForte}
    driverClassName: org.postgresql.Driver 
  jpa:
    show-sql: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: false
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
