#!/bin/bash
set -e

create_database(){
     psql -c "CREATE ROLE $DATABASE_USERNAME LOGIN ENCRYPTED PASSWORD '$DATABASE_PASSWORD' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;" 
     psql -c "CREATE DATABASE compasso ENCODING UTF8;" 
     psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to usuario;"
     psql -c "ALTER USER usuario WITH SUPERUSER;"
}

create_database $DATABASE_USERNAME $DATABASE_PASSWORD $DATABASE_NAME





